# Test 1: Python
Test some python code.

## 1. Import Packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 2. `pandas`

In [2]:
d1 = {'col1': [1, 2], 'col2': [3, 4]}
d2 = {'col1': [7, 8, 9, 10, 11, 12],
      'col2': [10, 20, 30, 40, 50, 60]}
df_1 = pd.DataFrame(data=d1)
df_2 = pd.DataFrame(d2)

df_1

col1  col2
0     1     3
1     2     4

In [3]:
df_2

col1  col2
0     7    10
1     8    20
2     9    30
3    10    40
4    11    50
5    12    60

In [4]:
list_df = [df_1, df_2]
list_df

[   col1  col2
 0     1     3
 1     2     4,
    col1  col2
 0     7    10
 1     8    20
 2     9    30
 3    10    40
 4    11    50
 5    12    60]

In [5]:
print(list_df[0] - df_1)
list_df[0] - df_1

   col1  col2
0     0     0
1     0     0


col1  col2
0     0     0
1     0     0

In [6]:
list_df[1] - df_2

col1  col2
0     0     0
1     0     0
2     0     0
3     0     0
4     0     0
5     0     0

##### Conclusion: `DataFrame` can be stored in a list.

In [7]:
list_df[0]['col1']

0    1
1    2
Name: col1, dtype: int64

In [8]:
list_df[1]['col2']

0    10
1    20
2    30
3    40
4    50
5    60
Name: col2, dtype: int64

In [9]:
list_df[1]['col1'][2]

9

##### Conclusion: I can select element.

In [10]:
for i in range(len(list_df)):
    print(i)
    print(list_df[i])
    print('-'*80)

0
   col1  col2
0     1     3
1     2     4
--------------------------------------------------------------------------------
1
   col1  col2
0     7    10
1     8    20
2     9    30
3    10    40
4    11    50
5    12    60
--------------------------------------------------------------------------------


## 3. [How to store multiple pandas DataFrame together](https://stackoverflow.com/questions/58841709/how-to-store-multiple-pandas-dataframes-together)

In [11]:
l = [pd.DataFrame(np.random.random((3,3)), columns=list('abc')) for _ in range(3)]
l

[          a         b         c
 0  0.522663  0.210987  0.592204
 1  0.824266  0.055793  0.380183
 2  0.506228  0.390542  0.033728,
           a         b         c
 0  0.493382  0.468280  0.466609
 1  0.421749  0.310982  0.854538
 2  0.281894  0.181331  0.409001,
           a         b         c
 0  0.594346  0.412980  0.209678
 1  0.238157  0.600135  0.969542
 2  0.907487  0.528245  0.237671]

In [12]:
l[0]['c']

0    0.592204
1    0.380183
2    0.033728
Name: c, dtype: float64

In [13]:
[df['c'] for df in l]

[0    0.592204
 1    0.380183
 2    0.033728
 Name: c, dtype: float64,
 0    0.466609
 1    0.854538
 2    0.409001
 Name: c, dtype: float64,
 0    0.209678
 1    0.969542
 2    0.237671
 Name: c, dtype: float64]

## 4. List

In [14]:
[i for i in range(3)]

[0, 1, 2]

In [15]:
[3 * i for i in range(10)]

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [16]:
[3 * i for i in range(10) if i > 4]

[15, 18, 21, 24, 27]

## 5. numpy

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
np.insert(a, 1, 5)

array([1, 5, 2, 3, 4, 5, 6])

In [8]:
np.insert(a, 1, [5, 6])

array([1, 5, 6, 2, 3, 4, 5, 6])

In [11]:
np.insert(a, [2, 4], [7, 9])

array([1, 2, 7, 3, 4, 9, 5, 6])

In [43]:
# define weight
weight_1 = np.array([1, 2, 3, 4, 5, 6])
weight2 = np.full(9, 2)
weight_2 = np.insert(weight2, 2, [4, 5, 6])

# define selected events
selected_1 = np.arange(6)
selected_2 = np.arange(9)

# create the lists of weight and selected
weight = [weight_1, weight_2]
selected = [selected_1, selected_2]

# create the dictionary of weight and selected
dict_weight = {'w1': weight_1, 'w2': weight_2}

In [44]:
print('list:')
print(weight)
print(selected)
print('-'*80)
print('dictionary:')
print(dict_weight)
dict_weight['w1']

list:
[array([1, 2, 3, 4, 5, 6]), array([2, 2, 4, 5, 6, 2, 2, 2, 2, 2, 2, 2])]
[array([0, 1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
--------------------------------------------------------------------------------
dictionary:
{'w1': array([1, 2, 3, 4, 5, 6]), 'w2': array([2, 2, 4, 5, 6, 2, 2, 2, 2, 2, 2, 2])}


array([1, 2, 3, 4, 5, 6])

In [52]:
# use basic and original way
print('basic way:')
print(weight_1[selected_1])
print(weight_2[selected_2])
print('-'*80)

# use lists of weight and selected 
print('list:')
print(weight[0][selected[0]])
print(weight[1][selected[1]])
print('-'*80)

# use dict of weight
print('dictionary:')
print(dict_weight['w1'][selected_1])
print(dict_weight['w2'][selected_2])

basic way:
[1 2 3 4 5 6]
[2 2 4 5 6 2 2 2 2]
--------------------------------------------------------------------------------
list:
[1 2 3 4 5 6]
[2 2 4 5 6 2 2 2 2]
--------------------------------------------------------------------------------
dictionary:
[1 2 3 4 5 6]
[2 2 4 5 6 2 2 2 2]
