# Test 0: Python Function
Just test the python function

## 1. Import Packages

In [1]:
# The Python Standard Library
import os
import sys
import time
import datetime
import glob
import multiprocessing as mp

# The Third-Party Library
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tqdm
import prettytable
import uproot
import pyjet
import importlib

## 1. List
* list
* tuple
* set
* append
* extend

### 1-1. list and tuple

In [2]:
a = [[1, 2], [3, 4]]
a

[[1, 2], [3, 4]]

In [3]:
b = [(1, 2), (3, 4)]
b

[(1, 2), (3, 4)]

In [4]:
a[0][0] = 10
a

[[10, 2], [3, 4]]

In [5]:
b[0][0] = 10
b

TypeError: 'tuple' object does not support item assignment

In [6]:
b[0] = [10, 20]
b

[[10, 20], (3, 4)]

##### Conclusion: `tuple` cannot be changed element, but entire tuple can be replaced by other object.

In [7]:
c = (1, 2, 3)
c

(1, 2, 3)

In [8]:
c[1]

2

In [9]:
c[1] = [20]

TypeError: 'tuple' object does not support item assignment

### 1-2. set, list, extend, and append

In [10]:
a = [1, 2, 3, 4, 3, 2, 5, 6]
set(a)

{1, 2, 3, 4, 5, 6}

In [11]:
b = list(set(a))
b

[1, 2, 3, 4, 5, 6]

In [12]:
b[0]

1

##### Conclusion: `set` can extract independent elements.

In [13]:
b.append([0, 0, 0])
b

[1, 2, 3, 4, 5, 6, [0, 0, 0]]

In [14]:
print(b[6])

[0, 0, 0]


In [15]:
b.extend(b)
b

[1, 2, 3, 4, 5, 6, [0, 0, 0], 1, 2, 3, 4, 5, 6, [0, 0, 0]]

##### Conclusion: `append()` adds a object into list and `extend()` iterate element into list.

## 2. Condition
* if else
* while

### 2-1. while

In [16]:
a = 1
while a < 7:
    if (a % 2 == 0):
        print(a, 'is even', a % 2)
    else:
        print(a, 'is odd', a % 2)
    a += 1

1 is odd 1
2 is even 0
3 is odd 1
4 is even 0
5 is odd 1
6 is even 0


## 3. Dictionary

In [8]:
# example
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [9]:
# dictionary items
thisdict["brand"]

'Ford'

In [10]:
# dictionary length
len(thisdict)

3

In [12]:
# duplicated not allowed
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}


In [13]:
# dictionary items can be of any data type
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}
thisdict

{'brand': 'Ford',
 'electric': False,
 'year': 1964,
 'colors': ['red', 'white', 'blue']}

In [14]:
# type()
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))

<class 'dict'>


In [15]:
# ordered??
thisdict[1]

KeyError: 1

## 3. NumPy

### 3-1 array(), index, dtype=, 

#### a. `array()`

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([(1, 2), (3, 4)])
b

array([[1, 2],
       [3, 4]])

In [18]:
a - b

array([[0, 0],
       [0, 0]])

In [19]:
b[0][0] = 10
b

array([[10,  2],
       [ 3,  4]])

##### Conclusion a: `tuple` in np.array() is not `tuple`, it will be changed to [].

#### b. `index`

In [20]:
d = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]
d = np.array(d)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
d[:, 0]

array([ 1,  5,  9, 13])

#### c. `dtype=`

In [22]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x['a']

array([1, 3], dtype=int32)

In [23]:
x[0]

(1, 2)

In [24]:
x[0][0] = 10
x

array([(10, 2), ( 3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])

##### Conclusion c: It is not `tuple`, the data is labeled to `'a'` and `'b'`. And the element can be changed.

In [25]:
a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
b = np.array([(5, 6), (7, 8)], dtype=[('x', 'i4'), ('y', 'i4')])
np.shape(a)

(2,)

In [26]:
a.shape

(2,)

In [27]:
a - b

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype([('x', '<i4'), ('y', '<i4')]), dtype([('x', '<i4'), ('y', '<i4')])) -> dtype([('x', '<i4'), ('y', '<i4')])

In [30]:
print(a[0])
b[0]


(1, 2)


(5, 6)

In [31]:
a[0] - b[0]

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype([('x', '<i4'), ('y', '<i4')]), dtype([('x', '<i4'), ('y', '<i4')])) -> dtype([('x', '<i4'), ('y', '<i4')])

In [33]:
a['x'] - b['x']

array([-4, -4], dtype=int32)

In [34]:
b['y'] - a['y']

array([4, 4], dtype=int32)

#### d. combine `array()`

In [35]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print(b.shape)

(2, 2)
(2, 3)


In [36]:
c = np.array([a, b])
c

ValueError: could not broadcast input array from shape (2,2) into shape (2)

In [37]:
c = [a, b]
c

[array([[1, 2],
        [3, 4]]),
 array([[1, 2, 3],
        [4, 5, 6]])]

In [38]:
print(c[0] - a)
print(c[1] - b)

[[0 0]
 [0 0]]
[[0 0 0]
 [0 0 0]]


##### Conclusion d: `np.array()` cannot apply different shape `array()` into `array()`.

## 4. pandas
* concat

#### a. `DataFrame`

In [3]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [4]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
df2

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
                dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df3 = pd.DataFrame(data, columns=['c', 'a'])
df3

c  a
0  3  1
1  6  4
2  9  7

In [7]:
data['c']

array([3, 6, 9], dtype=int32)

#### b. `concat`

In [39]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
df1

letter  number
0      a       1
1      b       2

In [40]:
df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])
df2

letter  number
0      c       3
1      d       4

In [41]:
pd.concat([df1, df2])

letter  number
0      a       1
1      b       2
0      c       3
1      d       4

## 5. time

In [2]:
print(time.strftime('%Y/%m/%d %a, %H:%M:%S %Z', time.localtime()))
start = datetime.datetime.now()
time.sleep(3)
end = datetime.datetime.now()
print('Time =', end - start)
print("\033[33mProgram Execution Time = {}\033[0m".format(end - start))

2022/04/21 Thu, 17:08:20 CST
Time = 0:00:03.003275
Program Execution Time = 0:00:03.003275


In [3]:
print(start)
end

2022-04-21 17:08:20.714738


datetime.datetime(2022, 4, 21, 17, 8, 23, 718013)

In [4]:
t1 = datetime.datetime.now()
time.sleep(3)
t2 = datetime.datetime.now()
print("\033[33mTime = {}\033[0m".format(t2 - t1))

t1 = datetime.datetime.now()
time.sleep(2)
t2 = datetime.datetime.now()
print("\033[33mTime = {}\033[0m".format(t2 - t1))

Time = 0:00:03.003452
Time = 0:00:02.002443


In [3]:
year = 2016
event = 'Referendum'
f'Results of the {year} {event}'

'Results of the 2016 Referendum'

In [9]:
f'A total number of {24 * 8 + 4}'

'A total number of 196'

In [4]:
rinv, Lambda_d = 0.3, 5
remark = 'test'
test_1 = ("status23_rinv" + str(int(rinv * 10)) +
        "_Lambdad" + str(Lambda_d) + "_" + remark)
test_1

'status23_rinv3_Lambdad5_test'

In [13]:
test_2 = f"status23_rinv{int(rinv * 10)}_Lambdad{Lambda_d}_{remark}"
test_2

'status23_rinv3_Lambdad5_test'

In [7]:
test_1 == test_2

True

In [8]:
type(test_2)

str

In [19]:
rinv, Lambda_d = 0.3, 5
remark = 'ckkwl_wo'
OUTPUT_PATH = '/youwei_u3/svj_data_master/scheme_1/analysis_script_v1'
# output_file = f"status23_rinv{int(rinv * 10)}_Lambdad{Lambda_d}_{remark}"
file = f"_rinv{int(rinv * 10)}_Lambdad{Lambda_d}_{remark}"
(OUTPUT_PATH + "/status23" + file + ".csv")

'/youwei_u3/svj_data_master/scheme_1/analysis_script_v1/status23_rinv3_Lambdad5_ckkwl_wo.csv'