# Test 11: Dark Sector
Check the constituent of dark sector and neutrino by using SVJ with CKKW-L and without decay data.

## 1. Import Packages

In [1]:
# The Python Standard Library
import os
import sys
import time
import datetime
import glob
import multiprocessing as mp

# The Third-Party Library
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tqdm
import prettytable
import uproot
import pyjet
import importlib

# My Packages
import myhep.particle_information_v2 as mypInfo_v2
import myhep.analytical_function_v2 as myaFun_v2
import myhep.analysis_v3 as myAnal_v3
# import myhep.particleinfo_v1 as mypiv1
# import myhep.particlefun_v1 as myafv1

# increase figure showing resolution
%config InlineBackend.figure_format = 'retina'

## 2. Import .root File and Load the Data via class
Skip:  
2-1. Check the number of events for each branch  
2-2. Define mass quantities

In [2]:
INPUT_FILE = '/youwei_u3/svj_data_master/scheme_1/root/ckkwl_wo.root'

DATA = uproot.open(INPUT_FILE)['Delphes;1']
GP = mypInfo_v2.classGenParticle(DATA)
Jet = mypInfo_v2.classJet(DATA)
Event = mypInfo_v2.classEvent(DATA)

## 3. Analyze the `Dark Sector` in the Parton and Truth Levels

### 3-1. Dark sector

In [3]:
myAnal_v3.dark_sector(GP)

* There is NO stable 4900101 in final state.
* There is NO stable 4900021 in final state.
* There is NO stable 4900111 in final state.
* There is NO stable 4900113 in final state.
* There is NO 4900102 in this dataset.
* There is NO 4900022 in this dataset.


##### Concluison: Well done!!

### 3-2. Neutrino

In [4]:
p12_s1, p14_s1, p16_s1 = myAnal_v3.neutrino(GP)

! 7385 events have the existence of electron neutrino (12) in final state.
! 7280 events have the existence of muon neutrino (14) in final state.
! 1353 events have the existence of tau neutrino (16) in final state.


In [6]:
print(f'12: {p12_s1[:10]}')
print(f'14: {p14_s1[:10]}')
print(f'16:')
p16_s1[:10]

12: [ 4 14 15 20 21 22 23 25 26 27]
14: [ 0  4  7 11 14 15 19 21 23 25]
16:


array([ 22,  30,  57, 103, 134, 160, 204, 206, 208, 227])

##### Conclusion: Well done!!

## 4. Test

In [7]:
# event 0
dfGP = GP.dataframelize(0)
dfGP

PID  Status   M1  M2  D1  D2         Mass            PT         Eta  \
0         -1      21    4  -1   3   3     0.000000  0.000000e+00  999.900024   
1          1      21    5  -1   3   3     0.000000  0.000000e+00 -999.900024   
2         21      43    5  -1   7   8     0.000000  1.062366e+01   -3.775406   
3    5000001      22    0   1   6   6  1533.499878  0.000000e+00 -999.900024   
4         -1      42    9  -1   0   0     0.000000  1.991679e-13  999.900024   
..       ...     ...  ...  ..  ..  ..          ...           ...         ...   
466       22       1  460  -1  -1  -1     0.000000  7.002710e+00    0.014616   
467       22       1  461  -1  -1  -1     0.000000  2.643003e-01    0.508933   
468       22       1  461  -1  -1  -1     0.000000  1.663036e+00    0.698884   
469       22       1  462  -1  -1  -1     0.000000  5.584304e-02   -0.126999   
470       22       1  462  -1  -1  -1     0.000000  3.539121e-01    0.442693   

          Phi  
0    0.000000  
1    0.000000  
2   -2.971525  
3    0.000000  
4   -2.971312  
..        ...  
466  0.035941  
467 -1.055437  
468 -0.982884  
469 -0.068835  
470 -0.856121  

[471 rows x 10 columns]

In [8]:
pid = dfGP['PID'].to_numpy()
pid[:10]

array([     -1,       1,      21, 5000001,      -1,       1, 5000001,
            21,      21,      -1], dtype=int32)

In [9]:
pid[(pid == 5000001	) | (abs(pid) == 4900101)]

array([ 5000001,  5000001,  5000001,  4900101, -4900101,  4900101,
       -4900101,  4900101, -4900101, -4900101, -4900101, -4900101,
        4900101, -4900101], dtype=int32)

In [10]:
pid_2 = pid[(pid == 4900102) | (pid == 4900022)]
pid_2

array([], dtype=int32)

In [11]:
pid_2.shape

(0,)